[package]
name = "security_cam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cfg-if = "1"
opencv = { version = "0.88", features = ["videoio"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "io-util", "sync", "time"] }

[features]
default = []
bgr2rgb = []
